### ISSUE TITLE
老哥，用不了啊

### ISSUE THREAD

**Issue by RexkentZheng** [ngxu/react-native-rn-videoplayer#1]
好容易安装完了，调用直接GG
```
import Videoplayer from 'react-native-rn-videoplayer';

export default ({ navigation }) => {
  return (
    <>
      <StatusBar barStyle="dark-content" hidden={false} />
      <SafeAreaView>
        <ScrollView
          contentInsetAdjustmentBehavior="automatic"
          style={styles.scrollView}>          
          <View style={styles.body}>
            <Text style={styles.sectionTitle}>Step One</Text>
            <Button
              title="Jump to Video"
              onPress={() => navigation.navigate('Video')}
            />
            <VideoPlayer
              url="https://jingdian.qincai-zuida.com/20200609/8136_0462c8a7/index.m3u8"
            />
          </View>
        </ScrollView>
      </SafeAreaView>
    </>
  );
}
```
报错如下：
![image](https://user-images.githubusercontent.com/17478325/84240282-61741980-ab30-11ea-9e52-6bcc9662e23e.png)
在线等，挺急的

**Comment by RexkentZheng** [comment]
没事了，老哥，现在开始报别的错了
![image](https://user-images.githubusercontent.com/17478325/84241144-a64c8000-ab31-11ea-8a60-8ebbaaff2eb7.png)

**Comment by A-ANing** [comment]
@RexkentZheng 你rn是什么版本

**Comment by RexkentZheng** [comment]
> @RexkentZheng 你rn是什么版本

0.62.2，老哥回得好快

**Comment by A-ANing** [comment]
> > @RexkentZheng 你rn是什么版本
> 
> 0.62.2，老哥回得好快

图二那个问题你要去看看react-native-linear-gradient这个库是怎么链接0.6以上的，我这是基于rn0.59.8做的

**Comment by RexkentZheng** [comment]
0.6以上好像就不用Link了，我去看看别的资料，谢谢老哥

**Comment by A-ANing** [comment]
> 0.6以上好像就不用Link了，我去看看别的资料，谢谢老哥

好嘞，0.6以上我没运行过。 不好意思

**Comment by RexkentZheng** [comment]
没事没事，开源的能贡献出来就已经很感激了。
这个ISSUE先别关，等我解决了再来提供解决办法。
辛苦老哥了

**Comment by RexkentZheng** [comment]
还有一个问题，老哥，下面的报错应该则么操作 @ngxu 
![image](https://user-images.githubusercontent.com/17478325/84246550-5d002e80-ab39-11ea-8957-b200935a4fbc.png)
addPackages那块的代码是这样的：
```
private final ReactNativeHost mReactNativeHost =
      new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          packages.add(new RNVideoplayerPackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }
      };
```

**Comment by ngxu** [comment]
> 还有一个问题，老哥，下面的报错应该则么操作 @ngxu
> ![image](https://user-images.githubusercontent.com/17478325/84246550-5d002e80-ab39-11ea-8957-b200935a4fbc.png)
> addPackages那块的代码是这样的：
> 
> ```
> private final ReactNativeHost mReactNativeHost =
>       new ReactNativeHost(this) {
>         @Override
>         public boolean getUseDeveloperSupport() {
>           return BuildConfig.DEBUG;
>         }
> 
>         @Override
>         protected List<ReactPackage> getPackages() {
>           @SuppressWarnings("UnnecessaryLocalVariable")
>           List<ReactPackage> packages = new PackageList(this).getPackages();
>           packages.add(new RNVideoplayerPackage());
>           return packages;
>         }
> 
>         @Override
>         protected String getJSMainModuleName() {
>           return "index";
>         }
>       };
> ```

把packages.add(new RNVideoplayerPackage())改成packages.add(new RNVideoplayerPackage());

**Comment by A-ANing** [comment]
> 还有一个问题，老哥，下面的报错应该则么操作 @ngxu
> ![image](https://user-images.githubusercontent.com/17478325/84246550-5d002e80-ab39-11ea-8957-b200935a4fbc.png)
> addPackages那块的代码是这样的：
> 
> ```
> private final ReactNativeHost mReactNativeHost =
>       new ReactNativeHost(this) {
>         @Override
>         public boolean getUseDeveloperSupport() {
>           return BuildConfig.DEBUG;
>         }
> 
>         @Override
>         protected List<ReactPackage> getPackages() {
>           @SuppressWarnings("UnnecessaryLocalVariable")
>           List<ReactPackage> packages = new PackageList(this).getPackages();
>           packages.add(new RNVideoplayerPackage());
>           return packages;
>         }
> 
>         @Override
>         protected String getJSMainModuleName() {
>           return "index";
>         }
>       };
> ```
你试试不手动link 因为你是rn0.6 自动link的  报错信息也是说这个模块被创建了两次

**Comment by RexkentZheng** [comment]
> > 还有一个问题，老哥，下面的报错应该则么操作 @ngxu
> > ![image](https://user-images.githubusercontent.com/17478325/84246550-5d002e80-ab39-11ea-8957-b200935a4fbc.png)
> > addPackages那块的代码是这样的：
> > ```
> > private final ReactNativeHost mReactNativeHost =
> >       new ReactNativeHost(this) {
> >         @Override
> >         public boolean getUseDeveloperSupport() {
> >           return BuildConfig.DEBUG;
> >         }
> > 
> >         @Override
> >         protected List<ReactPackage> getPackages() {
> >           @SuppressWarnings("UnnecessaryLocalVariable")
> >           List<ReactPackage> packages = new PackageList(this).getPackages();
> >           packages.add(new RNVideoplayerPackage());
> >           return packages;
> >         }
> > 
> >         @Override
> >         protected String getJSMainModuleName() {
> >           return "index";
> >         }
> >       };
> > ```
> 
> 把packages.add(new RNVideoplayerPackage())改成packages.add(new RNVideoplayerPackage());

这块没看懂啊

**Comment by RexkentZheng** [comment]
> > 还有一个问题，老哥，下面的报错应该则么操作 @ngxu
> > ![image](https://user-images.githubusercontent.com/17478325/84246550-5d002e80-ab39-11ea-8957-b200935a4fbc.png)
> > addPackages那块的代码是这样的：
> > ```
> > private final ReactNativeHost mReactNativeHost =
> >       new ReactNativeHost(this) {
> >         @Override
> >         public boolean getUseDeveloperSupport() {
> >           return BuildConfig.DEBUG;
> >         }
> > 
> >         @Override
> >         protected List<ReactPackage> getPackages() {
> >           @SuppressWarnings("UnnecessaryLocalVariable")
> >           List<ReactPackage> packages = new PackageList(this).getPackages();
> >           packages.add(new RNVideoplayerPackage());
> >           return packages;
> >         }
> > 
> >         @Override
> >         protected String getJSMainModuleName() {
> >           return "index";
> >         }
> >       };
> > ```
> 
> 你试试不手动link 因为你是rn0.6 自动link的 报错信息也是说这个模块被创建了两次

不手动link应该去掉哪些代码呢？README上面的link过程一开始就没有操作过，很尴尬

**Comment by RexkentZheng** [comment]
尝试了很多办法依然无果，始终会报`AppBrightness`的错，如果去掉
```
packages.add(new RNVideoplayerPackage());
```
则会报别的包没有被引用的错，数量还不少
之后尝试了去掉该依赖中和`AppBrightness`有关的所有内容，依然无果
甚至尝试了添加：
```
public boolean canOverrideExistingModule() {        
    return true;    
  }
```
还是依旧报`AppBrightness`的错，毫无办法😿

**Comment by A-ANing** [comment]
已支持RN0.60+
