### ISSUE TITLE
请问下可以提供下demo吗？万分感谢！导入后报错

### ISSUE THREAD

**Issue by iCodeAnt** [ngxu/react-native-rn-videoplayer#11]
请问下可以提供下demo吗？万分感谢！导入后报错

 Error: Requiring module "node_modules/react-native-rn-videoplayer/index.js", which threw an exception: Invariant Violation: Native module cannot be null.

**Comment by iCodeAnt** [comment]
import VideoPlayer from 'react-native-rn-videoplayer';

这样导入后会报错0.63的react-native

**Comment by qilovehua** [comment]
#2 
我的解决#2后也报这个错，"react-native": "0.61.5"
说是要remove几个包，react-native-linear-gradient,react-native-orientation-locker,react-native-system-setting这3个在yarn.lock里有，package.json里面，没法remove。
@A-ANing

**Comment by qilovehua** [comment]
Invariant Violation: Native module cannot be null.

constructor
    NativeEventEmitter.js:36:6
<global>
    SystemSetting.js:11:21
loadModuleImplementation
    require.js:321:4
guardedLoadModule
    require.js:210:11
metroRequire
    require.js:128:6
<global>
    index.js:38
loadModuleImplementation
    require.js:321:4
guardedLoadModule
    require.js:210:11
metroRequire
    require.js:128:6

**Comment by A-ANing** [comment]
android [手动link一下](https://github.com/A-ANing/react-native-rn-videoplayer#android) 
ios 需要pod install

**Comment by iCodeAnt** [comment]
> android [手动link一下](https://github.com/A-ANing/react-native-rn-videoplayer#android)
> ios 需要pod install

感谢回复，有做pod install 还是报错，方便提供个小demo吗！

**Comment by motogod** [comment]
> android [手动link一下](https://github.com/A-ANing/react-native-rn-videoplayer#android)
> ios 需要pod install


pod install 沒有安裝到 library

**Comment by zscm** [comment]
大佬，"react-native": "0.62.2" 安卓正常，IOS报错，Invariant Violation: Native module cannot be null.，进入ios/下 pod install，还是提示这个Invariant Violation: Native module cannot be null.，有ios的简单的demo可以让看看吗？万分感谢

**Comment by qilovehua** [comment]
node_modules/react-native-rn-videoplayer/ 下没有ios目录，我感觉这个有问题

**Comment by zscm** [comment]
我初始化一个新工程就安装了这一个插件，也是报的nvariant Violation: Native module cannot be null.这个错，等作者大佬不忙的时候看看怎么回复

**Comment by zscm** [comment]
> node_modules/react-native-rn-videoplayer/ 下没有ios目录，我感觉这个有问题

将react-native-rn-videoplayer/package.json中的所用的几个插件拷贝到你自己的工程package.json，删除node_module，重新npm install，就可以了，安卓如果在application手动添加了package，注释掉就可以了，我测试了可以用

**Comment by A-ANing** [comment]
我想是跟package.json中的dependencies有关，必须要这几个版本的包，所以我没有分开install；不知道你们安装过后其余几个依赖包是在rn项目node_modules还是在react-native-rn-videoplayer/下生成的node_modules内呢
![image](https://user-images.githubusercontent.com/43433064/98086490-d0745500-1eb9-11eb-8e06-2213570e4116.png)

**Comment by A-ANing** [comment]
### Native module cannot be null 就是依赖包没有pod成功，检查podfile.lock文件中是否有安装这5个包

- 如果没有，删除项目中下面的包  可以手动删除  也可以`npm uninstall  xxxx`
```
react-native-linear-gradient
react-native-orientation-locker
react-native-svg
react-native-system-setting
react-native-video
```

- 然后复制下面的添加到自己项目的package.json中的dependencies内
```
"react-native-rn-videoplayer": "^2.2.9",
"react-native-linear-gradient": "^2.5.6",
"react-native-orientation-locker": "^1.1.8",
"react-native-svg": "^9.5.1",
"react-native-system-setting": "^1.7.2",
"react-native-video": "^5.0.2"
```

- 然后执行
```
npm i

cd ios

pod install
```

**Comment by A-ANing** [comment]
over

**Comment by qew4** [comment]
33% 卡在这里8分钟，dependencies of :react-native-rn-videoplayer:classpath
