### ISSUE TITLE
可以提供隐藏视频左上角返回的属性吗

### ISSUE THREAD

**Issue by aijason** [ngxu/react-native-rn-videoplayer#13]
可以提供隐藏视频左上角返回的属性吗

**Comment by A-ANing** [comment]
小屏的返回吗

**Comment by aijason** [comment]
是的

**Comment by A-ANing** [comment]
v2.2.8 showSmallCont = {false}小屏是否显示返回按钮，设为为true
@aijason  好了

**Comment by aijason** [comment]
是因为我安卓手机测试的缘故吗，设置这个属性在安卓上没效果。

**Comment by A-ANing** [comment]
更新到2.2.8了吗

**Comment by aijason** [comment]
更新了

**Comment by aijason** [comment]
<VideoPlayer
              url={uri}
              style={detailStyles.video}
              controls
              autoPlay={false}
              poster={cover}//视频封面
              resizeMode='cover'
              //ref={(ref)=>this.player=ref}
              lockControl={true}
              moreSetting={() => null}
              statusBar={() => null}
              storeComponent={() => null}
              showSmallCont={false}
            />

**Comment by aijason** [comment]
![Uploading image.png…]()

**Comment by aijason** [comment]
display:this.state.smallP?(this.props.showSmallCont?"flex":"none"):"flex", position: this.state.smallP?"relative":"absolute",

**Comment by aijason** [comment]
这样设置好使 https://www.haorooms.com/post/react_native_displaynoneabsulute

**Comment by aijason** [comment]
有空支持下进度条颜色自定义，辛苦了

**Comment by A-ANing** [comment]
下个版本我一下改了   10分钟

**Comment by aijason** [comment]
好的，非常感谢

**Comment by A-ANing** [comment]
2.2.9 android已修复showSmallCont  增加进度条颜色自定义
```
- speedColor 当前播放进度条颜色 "#e54602"

- dotColor 进度条上的圆点颜色 "#e54602"

- dotBorderColor 进度条上的圆点被按下时的边框颜色 "rgba(255,255,255,0.3)"

- bottomSpeedColor 最底部播放进度的颜色 "#e54602"

- cachColor 缓冲进度条颜色 "#ffffff"

- allSpeedColor 整个进度条颜色 "rgba(0,0,0,0.4)
```

**Comment by aijason** [comment]
稳
