### ISSUE TITLE
全屏且不展示选集属性时进度条的展示过高

### ISSUE THREAD

**Issue by aijason** [ngxu/react-native-rn-videoplayer#14]
![image](https://user-images.githubusercontent.com/13975853/98079859-7bcbdc80-1eaf-11eb-97a2-e37db48298f7.png)

**Comment by aijason** [comment]
后续有时间可支持设置全屏时支持标题的展示

**Comment by A-ANing** [comment]
这个边距 其实挺好的  离上下边框太近  反而不好看

**Comment by aijason** [comment]
可能看惯了今日头条视频，进度条比较贴底。

**Comment by A-ANing** [comment]
全屏 返回按钮右边增加标题展示  可以有

**Comment by aijason** [comment]
稳
