### ISSUE TITLE
在安卓下有bug，播放时的视频尺寸不对

### ISSUE THREAD

**Issue by wulaizi** [ngxu/react-native-rn-videoplayer#18]
安卓加载时尺寸是对的，播放时尺寸就不对了
全屏时，视频是侧过来了，实际上视频的宽高并没有改变，导致了横过来时时依然是小屏幕播放，只是横着的

**Comment by A-ANing** [comment]
[视频尺寸问题](https://github.com/react-native-community/react-native-video/issues/2046)

是这个问题吗

**Comment by wulaizi** [comment]
![47219286E2270E34C47528BDF2B70064](https://user-images.githubusercontent.com/33690834/99505846-4e595580-29bc-11eb-833b-f5a71f21b3df.jpg)

**Comment by A-ANing** [comment]
在你项目的settings.gradle里添加
```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

![image](https://user-images.githubusercontent.com/43433064/99506534-2fa78e80-29bd-11eb-8882-6b9f5ee0f53c.png)

**Comment by wulaizi** [comment]
能看到图片吗？可能需要修改下hosts

> 在你项目的settings.gradle里添加
> 
> ```
> include ':react-native-video'
> project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
> ```
> 
> ![图片](https://user-images.githubusercontent.com/43433064/99506534-2fa78e80-29bd-11eb-8882-6b9f5ee0f53c.png)

非常感谢，解决了

**Comment by A-ANing** [comment]
下次有空升级到视频依赖包修复视频尺寸的版本，先关闭
