### ISSUE TITLE
android 视频关闭后，状态栏背景颜色会变白色

### ISSUE THREAD

**Issue by hectorqin** [ngxu/react-native-rn-videoplayer#23]

**Comment by A-ANing** [comment]
你可以在页面挂载生命周期内 手动改变StatusBar

**Comment by hectorqin** [comment]
调用了没用==

**Comment by A-ANing** [comment]
看看你代码

**Comment by hectorqin** [comment]
` useEffect(() => {
    console.log('showVideo ', showVideo);
    if (!showVideo) {
      if (Platform.OS === 'android') {
        StatusBar.setBackgroundColor('#000');
        StatusBar.setTranslucent(false);
        StatusBar.setHidden(false);
      }
      StatusBar.setBarStyle('default');
    }
  }, [showVideo]);

  if (!showVideo) {
    return Platform.OS === 'android'
      ? // <Header width={Dimensions.get('screen').width} />
        null
      : null;
  }
  return (
      <VideoPlayer
        style={{flex: 1}}
        url={convertSource(pageInfo.url).uri}
        headers={convertSource(pageInfo.url).headers}
        ref={(ref) => {
          player = ref;
        }}
        statusBar={() => null}
        title={pageInfo.title}
        panSamplingTimes={5}
        smallCloseIcon={true}
        autoHide={false}
        lockControl={true} />)
`

**Comment by hectorqin** [comment]
全屏之后退出全屏，状态栏就会变白，调用接口设置无效

**Comment by A-ANing** [comment]
视频页你设置成沉浸式试下  
StatusBar.setBackgroundColor('rgba(0,0,0,0)');
StatusBar.setTranslucent(true);

**Comment by hectorqin** [comment]
`<StatusBar translucent={true} barStyle={'light-content'} />
      <VideoPlayer
        style={{
          flex: 1,
          paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
        }}
        url={convertSource(pageInfo.url).uri}
        headers={convertSource(pageInfo.url).headers}
        ref={(ref) => {
          player = ref;
        }}
        statusBar={() => null}`

还是没用

**Comment by A-ANing** [comment]
<StatusBar translucent={true} barStyle={'light-content'}  backgroundColor={"rgba(0,0,0,0)"}/>

我不知道你状态栏具体什么样  加上backgroundColor试试

**Comment by hectorqin** [comment]
算了，搞不定 ==
