### ISSUE TITLE
底部工具栏双击无法呼出

### ISSUE THREAD

**Issue by zinete** [ngxu/react-native-rn-videoplayer#3]

**Comment by A-ANing** [comment]
你指的是手机的home back导航按键？

**Comment by zinete** [comment]
如图，就是双击播放界面，偶尔无法弹出播放暂停页面  https://imgchr.com/i/aLEqdP

**Comment by A-ANing** [comment]
模拟器有点问题，试试用真机，要关掉debug浏览器调试。

**Comment by zinete** [comment]
好的非常感谢。我试试。我还有一个问题。我使用 react-navigation 怎么样在跳转到下一个页面停止播放上一个页面的的视频呢？

**Comment by A-ANing** [comment]
推荐你用最新2.0.4版本，双击暂停为如图所示。


![bb1b987fd29c6e891e851ed116ad697](https://user-images.githubusercontent.com/43433064/89862691-11bad880-dbdb-11ea-909e-7ab6a4140119.jpg)


2.0.4目前为了让单击能快速响应，显示控件，所以我取消了一个300ms内的一个判断，以前只会响应双击或者单击事件，现在双击的时候也会响应单击的事件。

也就是双击的时候，如果控件是显示状态，那么只显示已暂停，反之，控件和已暂停都会显示。

单击为显示或者隐藏控件；
双击为暂停播放，2.0.4版本也会响应单击事件哦；不影响已暂停的提示。

**Comment by A-ANing** [comment]
> 好的非常感谢。我试试。我还有一个问题。我使用 react-navigation 怎么样在跳转到下一个页面停止播放上一个页面的的视频呢？

这个你要参考react-navigation的钩子，https://reactnavigation.org/docs/function-after-focusing-screen
这里可能会找到你想要的。
this.player.setPaused(true)可以暂停视频

**Comment by zinete** [comment]
好的非常感谢。我目前用的就是2.0.4 版本但是在模拟器下，关闭debug模式。控件还是不易呼出

**Comment by A-ANing** [comment]
> 好的非常感谢。我目前用的就是2.0.4 版本但是在模拟器下，关闭debug模式。控件还是不易呼出

是的  ios模拟器有这个毛病，android没有。我也跟你一样。真机么问题就行啦，所以我也没有管这个

**Comment by zinete** [comment]
好的。

**Comment by A-ANing** [comment]
> 好的非常感谢。我目前用的就是2.0.4 版本但是在模拟器下，关闭debug模式。控件还是不易呼出

2.2.3版本已经修复，并优化手势功能。
