### ISSUE TITLE
CONFIGURING一直卡60

### ISSUE THREAD

**Issue by helishou** [ngxu/react-native-rn-videoplayer#30]
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
<=======------> 60% CONFIGURING [7m 8s]
<=======------> 60% CONFIGURING [7m 9s]e dependencies of :react-native-rn-videoplayer:classpath
<=======------> 60% CONFIGURING [7m 51s]

**Comment by A-ANing** [comment]
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
这个是警告 把dependencies 下的compile 修改成implementation

下面一直60  跟网络有关  可以试试代理  或者将dependencies改成你有的gradle版本

**Comment by helishou** [comment]
解决了,谢谢了.又学到了新的操作

**Comment by A-ANing** [comment]
好嘞 没事先关闭啦
