### ISSUE TITLE
视频全屏后,手势，播放按钮，进度条异常

### ISSUE THREAD

**Issue by imbricklayer** [ngxu/react-native-rn-videoplayer#6]
1:视频全屏后,手势，播放按钮，进度条异常
2:增加场景：播放地址在点击播放后后才获取并且才开始播放
3:在场景2的情况下没有url的情况进度条手势必须失效，点击播放获取播放地址后才重新生效

**Comment by A-ANing** [comment]
大兄弟，你好
1，我想问下问题1中，是什么平台，ios中发生的吗，由于近两个版本我优化了下手势，可不可以提供下平台，截图。
2，问题2，可以用paused={true}，就不会自动播放
3，我想我后面可以提供开关手势的方法。

**Comment by imbricklayer** [comment]
应该是我布局的问题，我还在一点点调试。
1：视频一般都是m3u8 而且url都有加密和时效性，一但超时就播放不了了，所以一般都是点击或双击播放的时候再去获取url，然后才自动播放
2：控件消失显示问题，因为加了很多动画 每个动画都有duration，就会导致点击视频显示或消失控件的时候会有一定延迟，很不好的体验

**Comment by A-ANing** [comment]
delay是延时执行动画，duration是动画持续时间，我控件显示隐藏duration设置的300，delay都是0，你试过关闭debug浏览器调试没，debug模式可能会有点延迟。

**Comment by A-ANing** [comment]
需要明细；暂时关闭

**Comment by A-ANing** [comment]
需要明细；暂时关闭
